# Generated by Django 3.1.7 on 2021-03-25 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_sport', models.CharField(max_length=50)),
                ('fav_team', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('team_one', models.CharField(max_length=50)),
                ('team_two', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WatchParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scheduled_time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('number_of_fans', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.fan')),
            ],
        ),
        migrations.CreateModel(
            name='WatchPartyFan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.fan')),
                ('watchparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.watchparty')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.sporttype'),
        ),
    ]
